name: d_c_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_ui_auth: ^1.16.0
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.6.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  floor_generator: ^1.5.0
  retrofit_generator: ^9.1.7
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
