// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1eWy84aVl-NudTZjnKBpg5tS7ceA1a2A',
    appId: '1:986401935827:web:d03e30471538b7a6cadf26',
    messagingSenderId: '986401935827',
    projectId: 'data-collection-app-11474',
    authDomain: 'data-collection-app-11474.firebaseapp.com',
    storageBucket: 'data-collection-app-11474.firebasestorage.app',
    measurementId: 'G-EN4EPFKBEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHvjb_1y4xzvKd6NAo2XyexPVb1Qb6xP0',
    appId: '1:986401935827:android:267701e2ab409e0ecadf26',
    messagingSenderId: '986401935827',
    projectId: 'data-collection-app-11474',
    storageBucket: 'data-collection-app-11474.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBaC3QoydIa6UYaVpThi5eUf_WsmkJO3g',
    appId: '1:986401935827:ios:4621ffd1bd74abfecadf26',
    messagingSenderId: '986401935827',
    projectId: 'data-collection-app-11474',
    storageBucket: 'data-collection-app-11474.firebasestorage.app',
    iosBundleId: 'com.example.dCApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBaC3QoydIa6UYaVpThi5eUf_WsmkJO3g',
    appId: '1:986401935827:ios:4621ffd1bd74abfecadf26',
    messagingSenderId: '986401935827',
    projectId: 'data-collection-app-11474',
    storageBucket: 'data-collection-app-11474.firebasestorage.app',
    iosBundleId: 'com.example.dCApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1eWy84aVl-NudTZjnKBpg5tS7ceA1a2A',
    appId: '1:986401935827:web:d2ace88cc469b15bcadf26',
    messagingSenderId: '986401935827',
    projectId: 'data-collection-app-11474',
    authDomain: 'data-collection-app-11474.firebaseapp.com',
    storageBucket: 'data-collection-app-11474.firebasestorage.app',
    measurementId: 'G-8HVER6GCTF',
  );
}
